### ISSUE TITLE
Error: there is no package called ‘DT’

### ISSUE THREAD

**Issue by mrustl** [INWTlab/ecom-analytics#2]
Selecting the "Example Dataset" and clicking on the "RawData" tab leads to the following error message:
`Error: there is no package called ‘DT’  `

Looks like your shiny app is not yet as robust as it should be ;-) 

Adding the R package 'DT' to the DESCRIPTION should help!

**Comment by aneudecker** [comment]
@mrustl Thanks for pointing this out! This is fixed in the current version.
